set_property PACKAGE_PIN A4 [get_ports out]
set_property PACKAGE_PIN K1 [get_ports {in[3]}]
set_property PACKAGE_PIN K2 [get_ports {in[2]}]
set_property PACKAGE_PIN L1 [get_ports {in[1]}]
set_property PACKAGE_PIN W2 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports {in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property PACKAGE_PIN M2 [get_ports {sel[1]}]
set_property PACKAGE_PIN N1 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]

set_property PACKAGE_PIN M1 [get_ports {in[0]}]
