set_property PACKAGE_PIN R2 [get_ports A]
set_property PACKAGE_PIN T1 [get_ports B]
set_property PACKAGE_PIN L1 [get_ports Y]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports Y]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
